version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: group1-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./data/db:/var/lib/mysql

