# Generated by Django 4.1.3 on 2025-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group5", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="group5/media/chat_files/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="group5/media/avatars/"
            ),
        ),
    ]
