# Generated by Django 4.1.3 on 2025-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcategory',
            name='image_path',
            field=models.CharField(blank=True, help_text="Full path or URL to image (e.g., 'static/images/categories/tech.jpg' or 'https://cdn.example.com/images/tech.jpg')", max_length=500, null=True),
        ),
    ]
