# Generated by Django 4.1.3 on 2025-07-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='group1.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='voice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('VOCAB', 'Vocab'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SENTENCE', 'Sentence Building')], max_length=20),
        ),
    ]
