# Generated by Django 4.1.3 on 2025-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group1', '0002_question_parent_question_question_voice_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
