# Generated by Django 4.1.3 on 2025-07-25 13:55

from django.db import migrations, models
import group3.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("group3", "0003_teacherattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=group3.storage_backends.TeacherAttachmentStorage(),
                upload_to="profiles/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=group3.storage_backends.TeacherAttachmentStorage(),
                upload_to="resumes/%Y/%m/%d/",
            ),
        ),
        migrations.DeleteModel(
            name="TeacherAttachment",
        ),
    ]
