# Generated by Django 4.1.3 on 2025-07-29 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group3", "0004_teacher_profile_picture_teacher_resume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="resume",
        ),
    ]
