# Generated by Django 4.1.3 on 2025-07-22 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Word ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='Word Text')),
                ('image_url', models.CharField(max_length=255, verbose_name='Image URL')),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, validators=[django.core.validators.MinValueValidator(1, message='Difficulty must be at least 1.'), django.core.validators.MaxValueValidator(3, message='Difficulty must be at most 3.')], verbose_name='Difficulty Level')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='group6.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'Words',
            },
        ),
        migrations.AddConstraint(
            model_name='words',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__in', [1, 2, 3])), name='difficulty_level_check'),
        ),
    ]
