# Generated by Django 4.1.3 on 2025-07-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('level', models.SmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, verbose_name='Current Level')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'User Level',
                'verbose_name_plural': 'User Levels',
                'db_table': 'user_level',
            },
        ),
        migrations.CreateModel(
            name='UserWordStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Stat ID')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Correct Guesses')),
                ('incorrect_count', models.IntegerField(default=0, verbose_name='Incorrect Guesses')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Last Updated')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='group6.words', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'User Word Stat',
                'verbose_name_plural': 'User Word Stats',
                'db_table': 'user_word_stats',
                'ordering': ['timestamp'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
